site_name: OnchainID Documentation
site_description: 'Official documentation for the OnchainID solution, an Identity ecosystem for digital assets holders to create blockchain identities to access and trade compliant digital assets.'
site_author: 'OnchainID Organization'
site_url: 'https://onchainid.com'
copyright: 'Copyright &copy; 2021 - tokeny solutions'
repo_name: 'onchain-id/documentation'
repo_url: 'https://github.com/onchain-id/documentation'
theme:
  name: 'material'
  custom_dir: 'theme/'
  palette:
    primary: 'Blue Grey'
    accent: 'Indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  logo:
    icon: 'chrome_reader_mode'
  language: 'en'
  favicon: 'images/OnchainID_icon.png'
extra:
  social:
    - type: 'github'
      link: 'https://github.com/onchain-id'
  links:
    onchainid: 'http://onchainid.com'
extra_css:
  - 'stylesheets/extra.css'
  - 'https://unpkg.com/mermaid@7.1.2/dist/mermaid.css'
extra_javascript:
  - 'https://unpkg.com/mermaid@7.1.2/dist/mermaid.min.js'
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
plugins:
  - search
  - markdownextradata
nav:
  - Home: index.md
  - Introduction: introduction.md
  - BlockChain:
    - What is Blockchain?: blockchain/blockchain-intro.md
    - Ethereum Blockchain: blockchain/ethereum.md
    - Smart contracts: blockchain/smart-contracts.md
    - Tokens:
      - ERC-20 Tokens: blockchain/ERC-20.md
      - T-REX Tokens:
        - The T-REX Standard: blockchain/T-REX.md
        - Tokenizing Securities: blockchain/Constraints-securities.md
        - Permissioned Tokens: blockchain/permissioned-tokens.md
        - On-chain Identities: blockchain/identity-management.md
  - Identities:
    - What is an Identity: identities/introduction.md
    - Basic Information: identities/information.md
    - Claims: identities/claims.md
    - Connect with Identity: identities/connect-with-identity.md
    - Sharing data: identities/grants.md
  - Developers:
    - Developers HomePage: developers/developers.md
    - The Identity SDK:
      - Home: developers/sdks/identity-sdk/identity-sdk.md
      - Get Started: developers/sdks/identity-sdk/get-started.md
      - Configuration: developers/sdks/identity-sdk/configuration.md
      - BlockChain Providers: developers/sdks/identity-sdk/blockchain-providers.md
      - Signing Challenges: developers/sdks/identity-sdk/signer-module.md
      - Examples: developers/sdks/identity-sdk/examples.md
    - Providers:
      - Information Providers:
        - What are they?: developers/providers/Information Providers/presentation.md
        - Specification: developers/providers/Information Providers/specification.md
      - Claim Issuers:
        - What are they?: developers/providers/Claim Issuers/presentation.md
        - Specification: developers/providers/Claim Issuers/specification.md
    - Constants:
      - Claim Topics: developers/constants/claim-topics.md
      - Claim Schemes: developers/constants/claim-schemes.md
      - Information Types: developers/constants/information-types.md
  - About:
    - License: license.md
